---
- hosts: "*"
  become: yes
  tasks:
    - name: Install python 2.7
      apt:
        name: "python2"
        state: latest
    - name: Install pip2
      apt:
        name: "python-pip"
        state: latest
    - name: Create a symbolic link for python (2/7 to _)
      ansible.builtin.file:
        src: /usr/bin/python2.7 
        dest: /usr/bin/python 
        owner: root
        group: root
        state: link
    - name: Create a symbolic link for pip (2 to _)
      ansible.builtin.file:
        src: /usr/bin/pip2 
        dest: /usr/bin/pip
        owner: root
        group: root
        state: link
    - name: Create a symbolic link for pip (2 to 3)
      ansible.builtin.file:
        src: /usr/bin/pip2
        dest: /usr/bin/pip3
        owner: root
        group: root
        state: link
    - name: Install DHCPD
      apt:
        name: "isc-dhcp-server"
        state: latest
    - name: Install requests python package
      ansible.builtin.pip:
        name: requests
    - name: Install requests toolbelt
      ansible.builtin.pip:
        name: requests_toolbelt
    - name: Install pysnmp
      ansible.builtin.pip:
        name: pysnmp
    - name: Install jinja2
      ansible.builtin.pip:
        name: jinja2
    - name: Install netaddr
      ansible.builtin.pip:
        name: netaddr
    - name: install netifaces
      ansible.builtin.pip:
        name: netifaces
    - name: Install isc_dhcp_leases
      ansible.builtin.pip:
        name: isc_dhcp_leases
    - name: Example clone of a single branch
      ansible.builtin.git:
        repo: https://github.com/packetsar/freeztp.git 
        dest: /opt/freeztp
